### ISSUE TITLE
[依頼]最終課題挙動確認

### ISSUE THREAD

**Issue by kishidashota** [deutzia186/freemarket_sample_67f#24]
■ URL
IPアドレス：52.196.36.244
Github（最終課題のリポジトリ）：freemarket_sample_67f

■ Basic認証
ID：admin
Pass：2222

■ テスト用アカウント
◯ 購入者用
メールアドレス：b@gmail.com
パスワード：1111111

◯ 購入用カード情報
番号：4242424242424242
期限：12/20
セキュリティカード：123

◯ 出品者用
メールアドレス：a@gmail.com
パスワード：1111111

**Comment by keisukekodama** [comment]
提出ありがとうございます！
確認させて頂いたところ、必須機能については問題ありませんでしたが、以下の不備が見受けられましたので修正をお願いします！

・出品している商品と値段
企業への提出物なので、以下の点を満たすよう実際のフリマアプリで出品されているような商品を出品しましょう。

```
出品数が少なすぎないか。最低でも10品目
出品内容・販売価格が適切か。服や靴、本などが無難です。
```


修正し次第、以下の完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfMuna4xX0zQ6_L8vRFrevse1I8VkCcdMp-24egzeH_JmIllg/viewform

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by keisukekodama** [comment]
申し訳ありません、上記ですがメッセージを送り間違えていました。
商品を出品後、再度報告フォームの提出お願いします。

https://docs.google.com/forms/d/e/1FAIpQLSfMuna4xX0zQ6_L8vRFrevse1I8VkCcdMp-24egzeH_JmIllg/viewform

**Comment by kishidashota** [comment]
わかりました。

2020年2月17日(月) 21:28 児玉啓督 <notifications@github.com>:

**Comment by kishidashota** [comment]
> 申し訳ありません、上記のLGTMについてですがメッセージを送り間違えていました。
> 商品を出品後、再度報告フォームの提出お願いします。
> 
> https://docs.google.com/forms/d/e/1FAIpQLSfMuna4xX0zQ6_L8vRFrevse1I8VkCcdMp-24egzeH_JmIllg/viewform

**Comment by kishidashota** [comment]
修正終わりました。

再度確認お願いします。

**Comment by keisukekodama** [comment]
迅速な修正ありがとうございます！
確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます!
